### ISSUE TITLE
semi-spacing rule is unnecessary here?

### ISSUE THREAD

**Issue by tunnckoCore** [Flet/eslint-config-semistandard#13]
It's the same as https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L135

**Comment by jokeyrhyme** [comment]
Good find :)

**Comment by Flet** [comment]
Cool, we can get rid of it!

**Comment by jokeyrhyme** [comment]
I wonder if we can drop down to just having the "semi" rule?

That seems to be how this starter kit toggles their version of Semi-Standard: https://github.com/davezuko/react-redux-starter-kit/wiki/FAQ:-Frequently-Asked-Questions#want-semicolons

**Comment by Flet** [comment]
I think having `no-extra-semi` still makes sense for semistandard. I think its still good to avoid:

```js
var x = 5;;
```
and
```js
function foo() {
    // code
};
```

That tip for switching in that starter kit is clever! I think `no-extra-semi` wouldn't apply when running `--fix` so the same trick works fine. The benefit of no-extra-semi comes later when folks are working in the code and potentially sprinkling semicolons where they are not needed.
