### ISSUE TITLE
Add tag and CHANGELOG entry for 8.0.0 

### ISSUE THREAD

**Issue by voxpelli** [Flet/eslint-config-semistandard#16]
Seems like the `8.0.0` is missing from both the changelog and the tags in the repo, would be neat to have both added 👍

**Comment by Flet** [comment]
I just pushed the tag up. The CHANGELOG will need to be updated though.

I update the CHANGELOG for `semistandard`, so I'll probably copy/paste the pertinent bullets into this repo. https://github.com/Flet/semistandard/blob/master/CHANGELOG.md
