### ISSUE TITLE
support eslint-config-standard v3

### ISSUE THREAD

**Issue by jokeyrhyme** [Flet/eslint-config-semistandard#3]
Thanks for this project. It's been very useful for me. :)

I just noticed that the peerDependency upon https://github.com/feross/eslint-config-standard is locked to "^2.0.0", which is preventing me from using this with the latest upstream version of that shared config.

Would you like a PR that allows both v2 and v3 of https://github.com/feross/eslint-config-standard ?

**Comment by Flet** [comment]
Ah looks like he bumped to 3.0.0 a few hours ago. I'll bump this tomorrow morning!

**Comment by jokeyrhyme** [comment]
Cheers! <3

**Comment by Flet** [comment]
@jokeyrhyme thanks for being patient! I've updated everything. Can you give it another try?

**Comment by jokeyrhyme** [comment]
Works great! Cheers! <3
