### ISSUE TITLE
support eslint-config-standard v4

### ISSUE THREAD

**Issue by jokeyrhyme** [Flet/eslint-config-semistandard#4]
Haha, it happened again! :)

https://github.com/feross/eslint-config-standard/releases/tag/v4.0.0-0

NPM v2 complains with an error if I'm trying to forcibly use this newer "standard" package. I've got around this for now with the NPM v3 beta, but it'd be super terrific if you could bump your package.json deps again.

Cheers! <3

**Comment by jokeyrhyme** [comment]
Oh, it'd be terrific if you allowed ESLint 1.0 as well:
http://eslint.org/blog/2015/07/eslint-1.0.0-rc-1-released/

Yay!

**Comment by Flet** [comment]
Thanks, yeah I was waiting for 1.0.0 to be out of rc before doing to much... so, lets get this going :)
