### ISSUE TITLE
Update npm peer dependencies to work with ESLint 2.0+

### ISSUE THREAD

**Issue by natorojr** [Flet/eslint-config-semistandard#8]
Hi,

I tried upgrading one of my projects to ESLint 2.0, but the upgrade failed due to peer dependency conflicts with eslint-config-semistandard

> npm ERR! peer dep missing: eslint@^1.0.0, required by eslint-config-semistandard@5.0.0
npm ERR! peer dep missing: eslint@^1.6.0, required by eslint-loader@1.2.1
npm ERR! peer dep missing: eslint-config-standard@^4.0.0, required by eslint-config-semistandard@5.0.0
npm ERR! peer dep missing: eslint-plugin-promise@^1.0.8, required by eslint-config-standard@5.1.0

Can you please update your dependencies to work with ESLint 2.0+?

Thanks!

**Comment by spamguy** [comment]
Same problem.

**Comment by nerijusgood** [comment]
Same here

**Comment by jokeyrhyme** [comment]
My PR covers this #7

**Comment by scic** [comment]
+1
Since 6.0.5 feross/standard is compatible with eslint 2.0.0:
https://github.com/feross/standard/blob/master/CHANGELOG.md#605---2016-02-12

**Comment by natorojr** [comment]
I'm not usually the nagging type, especially since I understand that open source projects are often maintained during the project owner's spare time. However, in this case, I feel the need to bump this request as it is now effecting all 7 projects I'm currently working on.

Dear @Flet, please consider upgrading the dependencies of this project to work with ESLint 2+. See PR #7 

Thanks in advance for your consideration.

**Comment by Flet** [comment]
Thanks for the nudge @natorjr

I was hoping to wait for the next major version of standard to be released, but it seems to be taking more time than I thought. 

I'll shore up semistandard in the next day or two.

**Comment by Flet** [comment]
published new major version `eslint-config-semistandard@6.0.0`... new rules from standard! I tried to capture all the new ones in the CHANGELOG
https://github.com/Flet/eslint-config-semistandard/blob/master/CHANGELOG.md

**Comment by natorojr** [comment]
Awesome. Thank you so much for your consideration.

Everything seems to be working on the 2 projects I've upgraded so far. Best!
